# ------------------------------------------------------------------------------
# Firebase Emulator for Tests local and CI
# ------------------------------------------------------------------------------

version: "2.1"

services:

  # -------------------------------------
  # Firebase Eumulator
  # -------------------------------------

  emu:
    build: .
    volumes:
      - ./firebase.json:/app/firebase.json
    ports:
      - 5001:5001
      - 9000:9000
      - 8080:8080
      - 8085:8085
      - 5000:5000
    entrypoint:
      ["firebase", "emulators:start"]
