# ------------------------------------------------------------------------------
# Firebase Emulator for Tests local and CI
# ------------------------------------------------------------------------------

version: "3.2"

services:

  # -------------------------------------
  # Firebase Eumulator
  # -------------------------------------
  emulator:
    entrypoint:
      ["/app/entrypoint.sh", "run_all"]